### ISSUE TITLE
Ensure design is effective and looking good v1.0

### ISSUE THREAD

**Issue by AlyxMoon** [AlyxMoon/lunar-factorio-mod-manager#104]
This is just a general catch-all issue for version 1.0 of release. Any notes related to the look and feel of the project that doesn't necessitate a new feature implementation can go here.

While it doesn't have to be 100%, my goal is to resemble the design of Factorio.

Here's a list of pending design changes:
- style the text input fields
- style the scrollbars
- keep display somewhere of mod downloads in progress (but less intrusive than the current toasts so it doesn't cover anything up)

**Comment by AlyxMoon** [comment]
- Style text input fields to match the look of the rest of the app

**Comment by mrdejong** [comment]
Are we going for the factorio ui look and feel?

**Comment by AlyxMoon** [comment]
Yes, that's the goal.
