### ISSUE TITLE
Add setting - close/open app when starting Factorio

### ISSUE THREAD

**Issue by AlyxMoon** [AlyxMoon/lunar-factorio-mod-manager#119]
There should be a toggleable option whether to close the app or not when the Start Factorio button is pressed.
I'm thinking close the app should be the default. Except in develop mode, should be keep the app open by default.

**Comment by mrdejong** [comment]
This isn't that difficult to implement. You want this on some a settings page or should the app ask that whenever the button "Start Factorio" is pressed?

**Comment by mrdejong** [comment]
Also you can assign this to me :)

**Comment by AlyxMoon** [comment]
Oh yeah, this is an easy one.

I wanted to have it on a separate page, I'll eventually think through what options I want to add later.
And you probably got an idea of how I'm storing data, but you can put all the settings in a 'settings' key in the config file.

**Comment by AlyxMoon** [comment]
As a heads up, I'm thinking about getting something started on this. I left the app hanging for a long time but this has been next on my todo :)

**Comment by mrdejong** [comment]
I already am working on this, you check my fork there is a branch there :)

Op vr 10 jan. 2020 om 15:23 schreef Allister <notifications@github.com>:

**Comment by mrdejong** [comment]
Gotta get back it this though :)

Op vr 10 jan. 2020 om 16:04 schreef DutchCaffeine <mrdejong89@gmail.com>:

**Comment by mrdejong** [comment]
Here is a link to the branch https://github.com/mrdejong/lunar-factorio-mod-manager/tree/feature/settings-page

**Comment by AlyxMoon** [comment]
Ah drat I hadn't looked at it in awhile, I didn't see the more recent commit.
Well I was just doing a little rework of how I'm initializing the main-side store and I think I'll finish that at least. Shouldn't be too hard to merge that together with your work. And I'll leave getting the settings page started to you. Thanks!

**Comment by AlyxMoon** [comment]
Just a heads up, I'm planning on working on more customizable profile settings and will do app settings along with it. Sometime in the next week.
I appreciate the interest in working on it, I hope you aren't too upset I'm going to steal this task out from under ya ;)
